name: CI

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: make
        run: make

  mandatory-tests:
    needs: build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: compilation
        run: make
      - name: assert
        if: always()
        run: |
          ./abstractVM tests/mandatory/task06/task.avm > output
          diff output tests/mandatory/task06/expected
      - name: add
        if: always()
        run: |
          ./abstractVM tests/mandatory/task07/task.avm > output
          diff output tests/mandatory/task07/expected
      - name: add2
        if: always()
        run: |
          ./abstractVM tests/mandatory/task08/task.avm > output
          diff output tests/mandatory/task08/expected
      - name: add3
        if: always()
        run: |
          ./abstractVM tests/mandatory/task09/task.avm > output
          diff output tests/mandatory/task09/expected
      - name: sub
        if: always()
        run: |
          ./abstractVM tests/mandatory/task10/task.avm > output
          diff output tests/mandatory/task10/expected
      - name: sub2
        if: always()
        run: |
          ./abstractVM tests/mandatory/task11/task.avm > output
          diff output tests/mandatory/task11/expected
      - name: sub3
        if: always()
        run: |
          ./abstractVM tests/mandatory/task12/task.avm > output
          diff output tests/mandatory/task12/expected
      - name: div
        if: always()
        run: |
          ./abstractVM tests/mandatory/task13/task.avm > output
          diff output tests/mandatory/task13/expected
      - name: div2
        if: always()
        run: |
          ./abstractVM tests/mandatory/task14/task.avm > output
          diff output tests/mandatory/task14/expected
      - name: div3
        if: always()
        run: |
          ./abstractVM tests/mandatory/task15/task.avm > output
          diff output tests/mandatory/task15/expected
      - name: mod
        if: always()
        run: |
          ./abstractVM tests/mandatory/task16/task.avm > output
          diff output tests/mandatory/task16/expected
      - name: mod2
        if: always()
        run: |
          ./abstractVM tests/mandatory/task17/task.avm > output
          diff output tests/mandatory/task17/expected
      - name: mul
        if: always()
        run: |
          ./abstractVM tests/mandatory/task18/task.avm > output
          diff output tests/mandatory/task18/expected
      - name: mul2
        if: always()
        run: |
          ./abstractVM tests/mandatory/task19/task.avm > output
          diff output tests/mandatory/task19/expected
      - name: dup
        if: always()
        run: |
          ./abstractVM tests/mandatory/task20/task.avm > output
          diff output tests/mandatory/task20/expected
      - name: pop
        if: always()
        run: |
          ./abstractVM tests/mandatory/task21/task.avm > output
          diff output tests/mandatory/task21/expected
      - name: print
        if: always()
        run: |
          ./abstractVM tests/mandatory/task22/task.avm > output
          diff output tests/mandatory/task22/expected
      - name: push
        if: always()
        run: |
          ./abstractVM tests/mandatory/task23/task.avm > output
          diff output tests/mandatory/task23/expected
      - name: swap
        if: always()
        run: |
          ./abstractVM tests/mandatory/task24/task.avm > output
          diff output tests/mandatory/task24/expected
      - name: clear
        if: always()
        run: |
          ./abstractVM tests/mandatory/task25/task.avm > output
          diff output tests/mandatory/task25/expected
      - name: clear2
        if: always()
        run: |
          ./abstractVM tests/mandatory/task26/task.avm > output
          diff output tests/mandatory/task26/expected
  push:
    if: github.ref == 'refs/heads/main'
    needs: [build, mandatory-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to main repo
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2025/B-SYN-400-NCY-4-1-abstractVM-hugo.kirch.git
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}