name: CI

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: make
        run: make al

  mandatory-tests:
    needs: build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: compilation
        run: make al
      - name: inline_comment
        if: always()
        run: |
          ./abstractVM tests/mandatory/task01/inline_comment.avm > output
          diff output tests/mandatory/task01/expected
      - name: inline_comment2
        if: always()
        run: |
          ./abstractVM tests/mandatory/task02/inline_comment2.avm > output
          diff output tests/mandatory/task02/expected
      - name: inline_comment3
        if: always()
        run: |
          ./abstractVM tests/mandatory/task03/inline_comment3.avm > output
          diff output tests/mandatory/task03/expected
      - name: assert
        if: always()
        run: |
          ./abstractVM tests/mandatory/task06/assert.avm > output
          diff output tests/mandatory/task06/expected
      - name: add
        if: always()
        run: |
          ./abstractVM tests/mandatory/task07/add.avm > output
          diff output tests/mandatory/task07/expected
      - name: add2
        if: always()
        run: |
          ./abstractVM tests/mandatory/task08/add2.avm > output
          diff output tests/mandatory/task08/expected
      - name: add3
        if: always()
        run: |
          ./abstractVM tests/mandatory/task09/add3.avm > output
          diff output tests/mandatory/task09/expected
      - name: sub
        if: always()
        run: |
          ./abstractVM tests/mandatory/task10/sub.avm > output
          diff output tests/mandatory/task10/expected
      - name: sub2
        if: always()
        run: |
          ./abstractVM tests/mandatory/task11/sub2.avm > output
          diff output tests/mandatory/task11/expected
      - name: sub3
        if: always()
        run: |
          ./abstractVM tests/mandatory/task12/sub3.avm > output
          diff output tests/mandatory/task12/expected
      - name: div
        if: always()
        run: |
          ./abstractVM tests/mandatory/task13/div.avm > output
          diff output tests/mandatory/task13/expected
      - name: div2
        if: always()
        run: |
          ./abstractVM tests/mandatory/task14/div2.avm > output
          diff output tests/mandatory/task14/expected
      - name: div3
        if: always()
        run: |
          ./abstractVM tests/mandatory/task15/div3.avm > output
          diff output tests/mandatory/task15/expected
      - name: mod
        if: always()
        run: |
          ./abstractVM tests/mandatory/task16/mod.avm > output
          diff output tests/mandatory/task16/expected
      - name: mod2
        if: always()
        run: |
          ./abstractVM tests/mandatory/task17/mod2.avm > output
          diff output tests/mandatory/task17/expected
      - name: mul
        if: always()
        run: |
          ./abstractVM tests/mandatory/task18/mul.avm > output
          diff output tests/mandatory/task18/expected
      - name: mul2
        if: always()
        run: |
          ./abstractVM tests/mandatory/task19/mul2.avm > output
          diff output tests/mandatory/task19/expected
      - name: dup
        if: always()
        run: |
          ./abstractVM tests/mandatory/task20/dup.avm > output
          diff output tests/mandatory/task20/expected
      - name: pop
        if: always()
        run: |
          ./abstractVM tests/mandatory/task21/pop.avm > output
          diff output tests/mandatory/task21/expected
      - name: print
        if: always()
        run: |
          ./abstractVM tests/mandatory/task22/print.avm > output
          diff output tests/mandatory/task22/expected
      - name: push
        if: always()
        run: |
          ./abstractVM tests/mandatory/task23/push.avm > output
          diff output tests/mandatory/task23/expected
      - name: swap
        if: always()
        run: |
          ./abstractVM tests/mandatory/task24/swap.avm > output
          diff output tests/mandatory/task24/expected
      - name: clear
        if: always()
        run: |
          ./abstractVM tests/mandatory/task25/clear.avm > output
          diff output tests/mandatory/task25/expected
      - name: clear2
        if: always()
        run: |
          ./abstractVM tests/mandatory/task26/clear2.avm > output
          diff output tests/mandatory/task26/expected
  extra-tests:
    needs: build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: compilation
        run: make al
      - name: big_number
        if: always()
        run: |
          ./abstractVM tests/extra/task01/big_number.avm > output
          diff output tests/extra/task01/expected
      - name: big_num_mul
        if: always()
        run: |
          ./abstractVM tests/extra/task02/big_num_mul.avm > output
          diff output tests/extra/task02/expected
      - name: big_num_mul2
        if: always()
        run: |
          ./abstractVM tests/extra/task03/big_num_mul2.avm > output
          diff output tests/extra/task03/expected
  push:
    if: github.ref == 'refs/heads/main'
    needs: [build, mandatory-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to main repo
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2025/B-SYN-400-NCY-4-1-abstractVM-hugo.kirch.git
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}