name: CI

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: make
        run: make

  mandatory-tests:
    needs: build

    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: compilation
        run: make
      - name: empty_avm
        if: always()
        run: |
          ./abstractVM tests/task00/task.avm > output
          diff output tests/task00/expected
      - name: empty_shell_input
        if: always()
        run: |
          cat tests/task01/input | ./abstractVM > output1
          diff output1 tests/task01/expected
      - name: simple test
        if: always()
        run: |
          ./abstractVM tests/task02/task.avm > output2
          diff output2 tests/task02/expected
      - name: int addition test
        if: always()
        run: |
          ./abstractVM tests/task03/task.avm > output3
          diff output3 tests/task03/expected
      - name: shell without exit statement
        if: always()
        run: |
          cat tests/task04/input | ./abstractVM 2>&1 | cat > output4
          diff output4 tests/task04/expected
      - name: program without exit statement
        if: always()
        run: |
          ./abstractVM tests/task05/task.avm 2>&1 | cat > output5
          diff output5 tests/task05/expected

      - name: Assert
        if: always()
        run: |
          ./abstractVM tests/task06/task.avm | cat > output6
          diff output6 tests/task06/expected

      - name: Add
        if: always()
        run: |
          ./abstractVM tests/task07/task.avm | cat > output7
          diff output7 tests/task07/expected

      - name: Add 2
        if: always()
        run: |
          ./abstractVM tests/task08/task.avm | cat > output8
          diff output8 tests/task08/expected

      - name: Add 3
        if: always()
        run: |
          ./abstractVM tests/task09/task.avm | cat > output9
          diff output9 tests/task09/expected

      - name: Sub
        if: always()
        run: |
          ./abstractVM tests/task10/task.avm | cat > output10
          diff output10 tests/task10/expected

      - name: Sub 2
        if: always()
        run: |
          ./abstractVM tests/task11/task.avm | cat > output11
          diff output11 tests/task11/expected

      - name: Sub 3
        if: always()
        run: |
          ./abstractVM tests/task12/task.avm | cat > output12
          diff output12 tests/task12/expected

      - name: Div
        if: always()
        run: |
          ./abstractVM tests/task13/task.avm | cat > output13
          diff output13 tests/task13/expected

      - name: Div 2
        if: always()
        run: |
          ./abstractVM tests/task14/task.avm | cat > output14
          diff output14 tests/task14/expected

      - name: Div 3
        if: always()
        run: |
          ./abstractVM tests/task15/task.avm | cat > output15
          diff output15 tests/task15/expected

      - name: Mod
        if: always()
        run: |
          ./abstractVM tests/task16/task.avm | cat > output16
          diff output16 tests/task16/expected

      - name: Mod 2
        if: always()
        run: |
          ./abstractVM tests/task17/task.avm | cat > output17
          diff output17 tests/task17/expected

      - name: Mul
        if: always()
        run: |
          ./abstractVM tests/task18/task.avm | cat > output18
          diff output18 tests/task18/expected

      - name: Mul 2
        if: always()
        run: |
          ./abstractVM tests/task19/task.avm | cat > output19
          diff output19 tests/task19/expected

      - name: Dup
        if: always()
        run: |
          ./abstractVM tests/task20/task.avm | cat > output20
          diff output20 tests/task20/expected

      - name: Pop
        if: always()
        run: |
          ./abstractVM tests/task21/task.avm | cat > output21
          diff output21 tests/task21/expected

      - name: Print
        if: always()
        run: |
          ./abstractVM tests/task22/task.avm | cat > output22
          diff output22 tests/task22/expected

      - name: Push
        if: always()
        run: |
          ./abstractVM tests/task23/task.avm | cat > output23
          diff output23 tests/task23/expected

      - name: Swap
        if: always()
        run: |
          ./abstractVM tests/task24/task.avm | cat > output24
          diff output24 tests/task24/expected

      - name: Clear
        if: always()
        run: |
          ./abstractVM tests/task25/task.avm | cat > output25
          diff output25 tests/task25/expected

      - name: Clear 2
        if: always()
        run: |
          ./abstractVM tests/task26/task.avm | cat > output26
          diff output26 tests/task26/expected


  extra-tests:
    needs: build

    runs-on: ubuntu-latest
    steps:
      - name: prout
        run: echo prout

  push:
    if: github.ref == 'refs/heads/main'
    needs: [build, mandatory-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to main repo
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2025/B-SYN-400-NCY-4-1-abstractVM-hugo.kirch.git
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
