name: CI

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: make
        run: make

  mandatory-tests:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: empty_avm
        run: |
          make
          mv tests/task00/task.avm ./task.avm
          ./abstractVM task.avm > output
          diff output tests/task00/expected
      - name: empty_shell_input
        run: |
          make
          mv tests/task01/input ./input
          cat input | ./abstractVM > output
          diff output tests/task00/expected

  extra-tests:
    needs: build

    runs-on: ubuntu-latest
    steps:
      - name: prout
        run: echo prout

  push:
    if: github.ref == 'refs/heads/main'
    needs: [build, mandatory-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to main repo
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2025/B-SYN-400-NCY-4-1-abstractVM-hugo.kirch.git
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
