name: CI

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: make
        run: make

  mandatory-tests:
    needs: build

    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: compilation
        run: make
      - name: empty_avm
        run: |
          mv tests/task00/task.avm ./task.avm
          ./abstractVM task.avm > output
          diff output tests/task00/expected
      - name: empty_shell_input
        run: |
          mv tests/task01/input ./input
          cat input | ./abstractVM > output
          diff output tests/task01/expected
      - name: simple test
        run: |
          mv tests/task02/task.avm ./task.avm
          ./abstractVM task.avm > output
          diff output tests/task02/expected
      - name: int addition test
        run: |
          mv tests/task03/task.avm ./task.avm
          ./abstractVM task.avm > output
          diff output tests/task03/expected
      - name: shell without exit statement
        run: |
          mv tests/task04/input ./input
          cat input | ./abstractVM 2>&1 | cat > output
          diff output tests/task04/expected
      - name: program without exit statement
        run: |
          mv tests/task05/task.avm ./task.avm
          ./abstractVM task.avm 2>&1 | cat > output
          diff output tests/task05/expected

      - name: Assert
        run: |
          mv tests/task06/task.avm ./task.avm
          ./abstractVM task.avm | cat > output
          diff output tests/task06/expected

      - name: Add
        run: |
          mv tests/task07/task.avm ./task.avm
          ./abstractVM task.avm | cat > output
          diff output tests/task07/expected

      - name: Add 2
        run: |
          mv tests/task08/task.avm ./task.avm
          ./abstractVM task.avm | cat > output
          diff output tests/task08/expected

      - name: Add 3
        run: |
          mv tests/task09/task.avm ./task.avm
          ./abstractVM task.avm | cat > output
          diff output tests/task09/expected

      - name: Sub
        run: |
          mv tests/task10/task.avm ./task.avm
          ./abstractVM task.avm | cat > output
          diff output tests/task10/expected

      - name: Sub 2
        run: |
          mv tests/task11/task.avm ./task.avm
          ./abstractVM task.avm | cat > output
          diff output tests/task11/expected

      - name: Sub 3
        run: |
          mv tests/task12/task.avm ./task.avm
          ./abstractVM task.avm | cat > output
          diff output tests/task12/expected

      - name: Div
        run: |
          mv tests/task13/task.avm ./task.avm
          ./abstractVM task.avm | cat > output
          diff output tests/task13/expected

      - name: Div 2
        run: |
          mv tests/task14/task.avm ./task.avm
          ./abstractVM task.avm | cat > output
          diff output tests/task14/expected

      - name: Div 3
        run: |
          mv tests/task15/task.avm ./task.avm
          ./abstractVM task.avm | cat > output
          diff output tests/task15/expected

      - name: Mod
        run: |
          mv tests/task16/task.avm ./task.avm
          ./abstractVM task.avm | cat > output
          diff output tests/task16/expected

      - name: Mod 2
        run: |
          mv tests/task17/task.avm ./task.avm
          ./abstractVM task.avm | cat > output
          diff output tests/task17/expected

      - name: Mul
        run: |
          mv tests/task18/task.avm ./task.avm
          ./abstractVM task.avm | cat > output
          diff output tests/task18/expected

      - name: Mul 2
        run: |
          mv tests/task19/task.avm ./task.avm
          ./abstractVM task.avm | cat > output
          diff output tests/task19/expected

      - name: Dup
        run: |
          mv tests/task20/task.avm ./task.avm
          ./abstractVM task.avm | cat > output
          diff output tests/task20/expected

      - name: Pop
        run: |
          mv tests/task21/task.avm ./task.avm
          ./abstractVM task.avm | cat > output
          diff output tests/task21/expected

      - name: Print
        run: |
          mv tests/task22/task.avm ./task.avm
          ./abstractVM task.avm | cat > output
          diff output tests/task22/expected

      - name: Push
        run: |
          mv tests/task23/task.avm ./task.avm
          ./abstractVM task.avm | cat > output
          diff output tests/task23/expected

      - name: Swap
        run: |
          mv tests/task24/task.avm ./task.avm
          ./abstractVM task.avm | cat > output
          diff output tests/task24/expected

      - name: Clear
        run: |
          mv tests/task25/task.avm ./task.avm
          ./abstractVM task.avm | cat > output
          diff output tests/task25/expected

      - name: Clear 2
        run: |
          mv tests/task26/task.avm ./task.avm
          ./abstractVM task.avm | cat > output
          diff output tests/task26/expected


  extra-tests:
    needs: build

    runs-on: ubuntu-latest
    steps:
      - name: prout
        run: echo prout

  push:
    if: github.ref == 'refs/heads/main'
    needs: [build, mandatory-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to main repo
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2025/B-SYN-400-NCY-4-1-abstractVM-hugo.kirch.git
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
