
name: tests

on:
  push

jobs:
  
  build-and-test:
    
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      
      - uses: actions/checkout@v3
      
      - name: make
        run: make
      
      - name: copy_bin
        run: cp abstractVM ./

      - name: empty_avm
        run: |
          cp tests/task00/task.avm ./tastk.avm
          ./abstractvm task.avm > comp
          diff expexted comp
